### ISSUE TITLE
Compile successfully but when I run the program will crash

### ISSUE THREAD

**Issue by rongloveyan** [kylemcdonald/ofxFaceTracker#107]
![1884394a-7bb3-4dcb-af5e-ae41e5fef7af](https://cloud.githubusercontent.com/assets/14213560/11420196/8c8b8502-9467-11e5-9844-c05ddc7b231c.png)
Using os x 10.11.1    Xcode 7.1.1

**Comment by rongloveyan** [comment]
of_v0.9.0_osx_release

**Comment by kylemcdonald** [comment]
please read the readme.
