### ISSUE TITLE
running slow when face not detected

### ISSUE THREAD

**Issue by bernardoaraujor** [kylemcdonald/ofxFaceTracker#111]
Hello.
I am doing some testing with the addon.
When I cover my face, the image starts to update really slowly.
Anyone knows why that happens, and wether there's any workaround for that?

Thanks.

**Comment by revisedagain** [comment]
This happens to me as well but only in low light

**Comment by genekogan** [comment]
not much you can do about this, but you may want to try [ofxFaceTracker2](https://github.com/HalfdanJ/ofxFaceTracker2) which doesn't have this problem so much.

**Comment by danomatika** [comment]
>Anyone knows why that happens,

It takes *lots* of math to find the face, hence the tracker runs at ~5 fps. Once it's found the face, it runs stably at ~30 fps as it doesn't have to do as much math.

>and wether there's any workaround for that?

Develop a new tracker?

**Comment by danomatika** [comment]
Also, please close this issue if you question is answered.

**Comment by genekogan** [comment]
[ofxFaceTracker2](https://github.com/HalfdanJ/ofxFaceTracker2) puts the tracker in a separate thread and runs at normal framerate, so try using that.

**Comment by kylemcdonald** [comment]
ofxFaceTracker can also run in a thread. check out https://github.com/kylemcdonald/ofxFaceTracker/tree/master/example-threaded/src for an example. i don't run it in a thread by default because there are a lot of situations where you want to do non-realtime or lowest-latency tracking.
