### ISSUE TITLE
Issue getting FaceOSC running on Windows

### ISSUE THREAD

**Issue by Deathlymonkey** [kylemcdonald/ofxFaceTracker#123]
Hi, not sure if this is the right place to ask, but here it goes

I've been trying to get FaceOSC running on Windows for a few days now and I can't seem to get it to work. To be completely honest, I'm not even sure I know how to run it since I really can't find any tutorial/information on the net.

I can run the templates (https://github.com/CreativeInquiry/FaceOSC-Templates) without error (I've tried the OF and Processing ones), but whenever I try to run FaceOSC all I get is a blank page.

Is it possible to get a semi-detailed explanation on how to run it? I'm pretty sure it could be a great thing to add to the read-me, I'm probably not the only person to have no clue how to run it.

Thanks a lot!

**Comment by genekogan** [comment]
can you provide more details? are you trying to use a pre-built executable or are you compiling it with openFrameworks? do you see an error message of some kind? it's hard to diagnose the issue without details. the readme is a semi-detailed explanation of how to run it. if there's something missing from it, let us know.

**Comment by Deathlymonkey** [comment]
I'm just not sure I understand which file to run. 

Starting from the beginning:

I download FaceOSC (from https://github.com/kylemcdonald/ofxFaceTracker/releases), unzip it...but then I'm not sure how to run it. Am I supposed to try and run it in Visual Studio (or any other programming environment)? Should there be an application file?

Also, after I've managed to run it, do I just run the template and  get access to the data from OSC?

I'm truly sorry if it's something trivial, I've never worked with OSC and I feel like I'm missing something.

Thanks a lot!

**Comment by Deathlymonkey** [comment]
After playing with it a bit more I've finally managed to get the app running.

Just gonna leave the steps here for anyone who might be as new to this as me and have no clue where to start (I'm using Visual Studio):

1. Install openFrameworks

2. Install ofxCv and try the examples - make sure they work properly. To run them, import them to Visual Studio with the Project Generator.

3. Download ofxFaceTracker. Add its folder to the openFrameworks addons folder. Copy the content of /libs/FaceTracker/model/ to bin/data/model/ of each ofxFaceTracker example you want to run (if you only want to run FaceOSC, then you only have to do it for this specific example.

4. Import FaceOSC to Visual Studio via the openFrameworks project generator.

5. Try to get FaceOSC running. If you get the LNK2019 and LNK2001 trackingdistance error messages, then do as described in this link (https://github.com/kylemcdonald/ofxFaceTracker/issues/115 ) to solve it , or this one (http://taka-say.hateblo.jp/entry/2016/02/24/200941 ) if you want images.

If you get a fatal error C1041, the 2nd answer in this thread (http://stackoverflow.com/questions/20643370/visual-studio-2013-fatal-error-c1041-fs ) solved it for me.

I also had another issue where there was literally no property to change after I clicked the project Properties (to solve the LNK2019 and LNK2001 issues); the C/C++ option wasn't there. I had to reinstall my Visual Studio to get it back. 

After you get the app running, you can use the templates (see my OP) to gain access to the OSC data.


I hope this can help other people who had the same issues as me as it took me a pretty long time before successfully running FaceOSC.
