### ISSUE TITLE
“ofMain.h”: No such file or directory

### ISSUE THREAD

**Issue by jackweiwang** [kylemcdonald/ofxFaceTracker#124]
![image](https://cloud.githubusercontent.com/assets/19305790/15180530/c6ec2f32-17b4-11e6-8fcc-0bd5acbf3b76.png)

I have attached the directory, why will appear this problem, I do not see lib below the header file

**Comment by genekogan** [comment]
have you placed ofxFaceTracker inside the `addons` folder? if it's not in there, the project file can't find the openFrameworks root folder, and is a reason you might get this error.  
see the other addons inside the addos folder? like ofxKinect, ofxOsc, and others? make sure ofxFaceTracker is inside there.

**Comment by jackweiwang** [comment]
I follow this step and openFrameworks/addons this folder should be where to find it? I did not find this so I downloaded the /ofxCv-master folder changed into the name on the following, it is wrong to see how I should be how to make him successful novice to help
