### ISSUE TITLE
Broken link FaceOSC

### ISSUE THREAD

**Issue by kasperkamperman** [kylemcdonald/ofxFaceTracker#130]
The link to FaceOSC seems broken and gives the message: There aren’t any uploads for this repository.

_If you would like to prototype an idea involving face tracking, I encourage you to download [FaceOSC](https://github.com/kylemcdonald/ofxFaceTracker/downloads)._ 

I can't find a executable in the repo either. I think it's a fast and easy tool for students to experiment with, so I hope you can share it again.

**Comment by genekogan** [comment]
fixed the link. you can get FaceOSC in the [releases page](https://github.com/kylemcdonald/ofxFaceTracker/releases).
