### ISSUE TITLE
FaceOSC for iOS?

### ISSUE THREAD

**Issue by drscotthawley** [kylemcdonald/ofxFaceTracker#145]
I've gotten FaceTracker to build and run on my iPhone 7, and would like to use it to send OSC codes.  

Now, I noticed that there are Windows and Mac binaries for FaceOSC, but not one for iOS.  So, I am  attempting to build FaceOSC for iOS. Just though I'd ask before trying to do this myself: Has anyone already succeeded in doing this? 

Presumably the keyboard controls for FaceOSC will not be available in iOS.

**Comment by drscotthawley** [comment]
Success: Posting here:  https://github.com/drscotthawley/FaceOSC-iOS

Feel free to close, and/or I can submit a PR.

**Comment by kylemcdonald** [comment]
cool! what would be awesome is if you could submit a PR that edits the readme to link to your code under the iOS section https://github.com/kylemcdonald/ofxFaceTracker/#ios

**Comment by drscotthawley** [comment]
@kylemcdonald Ok!  Sorry it took me so long to get to this!  PR on the way.
