### ISSUE TITLE
No more support for 0.9.8?

### ISSUE THREAD

**Issue by samhains** [kylemcdonald/ofxFaceTracker#148]
Hey,

I can't seem to figure out how to compile this in my version of 0.9.8. I've been having problems getting the nightly build's project generator working on my windows machine so unfortunately I am stuck on the stable version for now....

The master branch version of ofxFaceTracker didn't compile in vs2015 so I have tried to get it to compile it with repository checked out at commit #df00be.  This commit seemed to be around the time that the repository starting moving towards 0.10.0.

I have no problem compiling ofxCv and ofxOpenCv - compilation issues only occur when I add ofxFaceTracker.

This is a display of my compilation error:
![image](https://user-images.githubusercontent.com/7479037/38645807-673722dc-3db3-11e8-8b1f-4dcba2b7f30d.png)

Thanks,

Sam

**Comment by kylemcdonald** [comment]
Downloads/tagged versions for different versions of OF are available on the tags page https://github.com/kylemcdonald/ofxFaceTracker/tags
