### ISSUE TITLE
To make it to work for MacOS Catalina?

### ISSUE THREAD

**Issue by enzyme69** [kylemcdonald/ofxFaceTracker#166]
Is there anyway we can make the app to work in MacOS Catalina?

**Comment by kylemcdonald** [comment]
I believe Catalina requires 10.2, so please see  #164

**Comment by veacks** [comment]
@enzyme69 Found a trick to make 10.1 workings on Catalina:

First, run the build until it fails, then with terminal do the following

```sh
$ cd my-app.app/bin/my-appDebug.app/Contents/Frameworks/
$ codesign -s "<your-comp-name>" libfmodex.dylib
```
Then open your app manually
