### ISSUE TITLE
Error: -67456

### ISSUE THREAD

**Issue by pierrextardif** [kylemcdonald/ofxFaceTracker#167]
Hi,

I'm trying to get the addon to work with OF 10.0.1 on Mac OS  Mojave (10.14.6).

All the examples seem to compile fine, but the console gives me this (This is for the blink example ) : 
`2019-09-06 17:17:22.657632+0100 example-blinkDebug[2685:64821] [] CMIO_Unit_ScopeElement.h:200:SafeGetElement Throwing err: -67454
2019-09-06 17:17:22.658557+0100 example-blinkDebug[2685:64821] [] CMIOUnitFigBaseObjectImpl.c:246:CMIOUnitCreateFromDescription Invalid paramater
2019-09-06 17:17:22.672878+0100 example-blinkDebug[2685:64821] [] CMIO_Unit_Input_Device.cpp:244:GetPropertyInfo CMIOUInputFromProcs::GetPropertyInfo() failed for id 102, Error: -67456`

Then it seems like no processing happens ( _tracking not working_ but everything else seem to work fine).

The weird thing is that it worked the very first time i used it then nothing...

I tried : 
* using the nightly builds ( OFxCV uses some conversions macros which are not recognised by the nightly builds ( convert to Gray) );
* using the release tagged 1.1;
* clean and re - run the example;
*  compile for debugg & for release // run executable inside the packages as admin.

None of it has worked so far...

Help?

Thanks for the great work though,

++

P

**Comment by kylemcdonald** [comment]
Closing, as I've been unable to recreate this issue on 10.15 with OF 0.10.1
