### ISSUE TITLE
Constantly Searching for Face - macOS 10.15 

### ISSUE THREAD

**Issue by vladkoval009** [kylemcdonald/ofxFaceTracker#168]
Hi there,

This is an amazing add-on but it seems like there is no way for me use it under macOS Catalina. I have done my research on the issue and it seems its thx to apple as they deprecated QTKit from the latest release. When I run the program, the terminal is trying to do this: [ error ] ofQTKitGrabber: confirmInit(): calling method on unintialized video grabber. 

This is what apple website states regarding the changes:

AVFoundation
New Features
The AVPlayer class includes two new properties, eligibleForHDRPlayback and eligibleForHDRPlaybackDidChangeNotification, which you can use to determine whether an HDR display is available and can play on the current device. (35938145)
AVFoundation now supports encoding video with alpha channels using HEVC. Videos encoded in this manner are broadly supported in AVFoundation APIs and by Safari within web pages. Technical details of the format can be found in the Interoperability Profile specification. (8045917)
Deprecations
The previously deprecated 32-bit QuickTime framework is no longer available in macOS 10.15.
The symbols for QTKit, which relied on the QuickTime framework, are still present but the classes are non-functional.

Is there any way to solve this problem?

Thank you

**Comment by avilleret** [comment]
Hi,

it does work on macos 10.15 with openframeworks 10.1.
If you see your webcam image, then it seems to work.
If you see "Searching for face" like the issue's subject suggested, then this is self-explaining : it is searching for face.
If you see your face but it can't find it, this might be an illumination issue. I just experienced this behavior, turning on the light is enough to make it work.
But I agree, it looks like it's not working and could be hard to debug.

**Comment by vladkoval009** [comment]
Hey! Thank you for getting back to me. 

The program is searching for my face but the view finder is grey/not receiving the footage from my webcam and the console says this: 

[ error ] ofQTKitGrabber: confirmInit(): calling method on unintialized video grabber

Would you be so kind to the share a recompiled src code from your Mac under 10.15 please? 
I really need this FaceOSC to work for my uni project... 
Thank you!^_^

**Comment by avilleret** [comment]
which openframeworks version are you using ? 
could you build a simple program that uses the webcam (for example the video/videoGrabberExample shipped with OpenFrameworks) ?
If this one doesn't work, then the issue might not be related to FaceOSC but to OpenFrameworks itself.

**Comment by vladkoval009** [comment]
I am using version 0.11.0
I have built something like that and it works just fine assessing my cam.

**Comment by avilleret** [comment]
Could you try with OpenFrameworks 0.10.1 instead of 0.11.0 ?
btw I'm pretty curious how you built FaceOSC against 0.11.0, I failed because of 0.11.0 is shipped with OpenCV 4 which ditched legacy header that FaceOSC needs. (see #164)

**Comment by vladkoval009** [comment]
I will try to use OF 0.10.1 . Although I think there are issues between OF 10 AND Xcode 11...
I can not compile Face OSC on my machine. I could create a simple program using Open cv 4. It runs well even with animated particles interacting with my hand waving

**Comment by avilleret** [comment]
> I can not compile Face OSC on my machine.

Ha ok, you used the binary available in the release section right ?
if so, then yes it doesn't work on macos 10.15 due to the lack of QuickTime. (hence the error you mentioned).

I didn't not see any issue with XCode and OF 0.10.1 on macos 10.15.
And you definitely need OF 0.10.1 (and not --0.10.2-- nor --0.11.0--) to build FaceOSC because of OpenCV.

You need OpenCV 3 to build FaceOSC as is. 
If you really want to use OF 0.11 or OpenCV 4 then you'll have to update the core libFaceTracker which is written in plain C with the legacy OpenCV API.
But this is not an easy work. 

I think the easiest way to do so is to rewrite the library in C++ directly with OpenCV 4.
And at the same time it would be nice to use a more recent face detector. HaarCascade have been superseded by neural network nowadays.

**Comment by kylemcdonald** [comment]
It will not be possible to get this running on OF 0.10.2 and higher (including 0.11.0) due to OpenCV 4.

I have updated the MacOS FaceOSC binary under "releases" to work with MacOS 10.15 (Catalina) using OF 0.10.1.
