### ISSUE TITLE
No video camera input on OS 10.15

### ISSUE THREAD

**Issue by F-PAIS** [kylemcdonald/ofxFaceTracker#169]
Hi, 
Despite my attempts to modify the camera index in settings, I couldn't have my camera detected so the screen keeps grey with the sentence > "searching for face...".

With El capitain it worked perfectly and I was only using the Face OSC (standalone) without any other software (e.g. Open Cv or OpenFrameworks).

Any ideas on how to fix this?

Thank you very much!

**Comment by avilleret** [comment]
this is related to #168 : the binary available for download has been made with OF 10.0 that relies on QuickTime for video grabbing.
QuickTime have been ditched by Apple after a long period of deprecation. 
So to make it works under macOS 10.14 and 10.15 you must rebuild the software with newer openFrameworks or hire somebody to build it for you.

**Comment by kylemcdonald** [comment]
I have updated the MacOS FaceOSC binary under "releases" to work with MacOS 10.15 (Catalina) using OF 0.10.1.

It will not be possible to get this running on OF 0.10.2 and higher (including 0.11.0) due to OpenCV 4.
