### ISSUE TITLE
reg. compiling ofxFaceTracker

### ISSUE THREAD

**Issue by tommysky** [kylemcdonald/ofxFaceTracker#32]
Hi, dear Kyle,

I tried your work, FaceOSC_win. It is AMAZING! I tried to compile ofxFaceTracker to get FaceOSC_win but met errors and hope get you helps. I use 64-bit windows 7 and VS2010.

---

The error is:
ContourFinder.obj : error LNK2019: unresolved external symbol "float __cdecl ofxCv::trackingDistance(class cv::Rect_<int> const &,class cv::Rect_<int> const &)" 

---
1. I downloaded "openFrameWork 0072 under VS2010" at ttp://www.openframeworks.cc/download/.
2. I  then downloaded  "ofxFaceTracker". I modified its file name "kylemcdonald-ofxFaceTracker-15060b2" as "ofxFaceTracker" and copied it into addons of "openFrameWrok at (..\of_v0072_vs2010_release\addons).
3. I found "ofxFraceTracker" needs "ofxCv" and then downloaded it and copied it into addons (same as above).
4. I run "projectGenerator.exe" of "openFramework" and added "ofxFraceTracker", "ofxOpenCv" and "ofxCv" as addons. After compiling generated "mySketch" using VS2010, I met the  error in the top. Plus, I added codes as what the page of ofxCv said.

---

I really hope to get your helps, because it is supposed to be helpful to my current project. Sorry to bother you. I'll appreciate for your supports.

**Comment by Shaderboy** [comment]
Hi all, I just tried compiling for windows with 0.9.7 and am running into the same issue. The empty example from ofxCv compiles with no problem, but the empty example for ofxFaceTracker gives me this output:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "float __cdecl ofxCv::trackingDistance(class cv::Rect_<int> const &,class cv::Rect_<int> const &)" (?trackingDistance@ofxCv@@YAMABV?$Rect_@H@cv@@0@Z) referenced in function "public: virtual class std::vector<unsigned int,class std::allocator<unsigned int> > const & __thiscall ofxCv::Tracker<class cv::Rect_<int> >::track(class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > const &)" (?track@?$Tracker@V?$Rect_@H@cv@@@ofxCv@@UAEABV?$vector@IV?$allocator@I@std@@@std@@ABV?$vector@V?$Rect_@H@cv@@V?$allocator@V?$Rect_@H@cv@@@std@@@4@@Z)	example-empty	C:\Users\chris\Documents\Projects\of_v0.9.7_vs_release\addons\ofxFaceTracker\example-empty\ContourFinder.obj	1	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "float __cdecl ofxCv::trackingDistance(class cv::Rect_<int> const &,class cv::Rect_<int> const &)" (?trackingDistance@ofxCv@@YAMABV?$Rect_@H@cv@@0@Z)	example-empty	C:\Users\chris\Documents\Projects\of_v0.9.7_vs_release\addons\ofxFaceTracker\example-empty\ObjectFinder.obj	1
```

This is in visual studio 2015

**Comment by ch3gr** [comment]
I am having the same issue as well on VS2015.

I tried to rename the Tracker class and all filenames, but with no luck yet. It compiled a blank project once, but I think something keeps reverting some of my changes and fails when I try to compile a different project.

**Comment by krisrok** [comment]
as @kylemcdonald already said 5 years ago, this should fix the issue without the renaming adventure:
## http://stackoverflow.com/a/3731643

i just wanted to make this tip more visible again

**Comment by reedjones** [comment]
> as @kylemcdonald already said 5 years ago, this should fix the issue without the renaming adventure:
> 
> ## http://stackoverflow.com/a/3731643
> i just wanted to make this tip more visible again

This worked for me
