### ISSUE TITLE
FaceOSC running but getting no image on OS X Mavericks‎

### ISSUE THREAD

**Issue by myildirim** [kylemcdonald/ofxFaceTracker#62]
It runs but stays like this.
On Macbook Pro, OS X Mavericks‎.

![screen shot 2013-11-23 at 1 28 33 pm](https://f.cloud.github.com/assets/56878/1607322/ecb87718-547d-11e3-8929-c12909f838b8.png)

**Comment by vadimgoncharov** [comment]
Same problem. OSX 10.10.4
https://github.com/downloads/kylemcdonald/ofxFaceTracker/FaceOSC.zip not working ("searching for face..." message with no video)
http://facetracker.net/downloads/FaceOSC-Mavericks.zip works fine

**Comment by genekogan** [comment]
this has been fixed with the latest version of FaceOSC, built for openframeworks 0.9.  it should work if you download the most recent [release](https://github.com/kylemcdonald/ofxFaceTracker/releases) or compile it yourself.

**Comment by Pagutierr** [comment]
> Thanks. FaceOsc failed when update to High Sierra (no image) but http://facetracker.net/downloads/FaceOSC-Mavericks.zip works perfect.
