### ISSUE TITLE
Threaded Facetracker lags on Windows

### ISSUE THREAD

**Issue by jasonlevine** [kylemcdonald/ofxFaceTracker#79]
Hey Kyle,

On OSX the threaded facetracker example runs in real-time but the same code on Windows is extremely laggy(feels like 10fps).  ofGetFrameRate() still returns 60, so I'm assuming the difference between platforms has something to do with how threading works.

Have you seen this behaviour?  I'm running the face tracker code from the latest commit in OF 0.8.3 with VS2012 express on Windows 8.1 (whoa! "from, in, with, on")

Thanks,
Jason

**Comment by kylemcdonald** [comment]
going to close this until someone else reports and can help me fix it.
