### ISSUE TITLE
FaceOSC(IN UBUNTU ):ofxxmlsettings:push Tag():tag"camera"not found

### ISSUE THREAD

**Issue by manojprabhakaran1** [kylemcdonald/ofxFaceTracker#82]
dear kylemcdonald,
                                 i my doing face tracking using u r code
from ofxfacetrcker
in faceosc folder i compile the code and get this error....
[ error ] ofxXmlSettings: pushTag(): tag "source" not found
[ error ] ofxXmlSettings: pushTag(): tag "camera" not found
[notice ] probing devices with udev...
[notice ] found device 046d:0825, getting capabilities...
[notice ] detected v4l2 device: UVC Camera (046d:0825)
[notice ] driver: uvcvideo, version: 199947
[notice ] capabilities: 0x84000001
[notice ] ofGstVideoGrabber: initGrabber(): selected device: UVC Camera (046d:0825)
[notice ] ofGstVideoGrabber: initGrabber(): selected format: 640x480 video/x-raw RGB framerate: 30/1
[notice ] ofGstUtils: setPipelineWithSink(): gstreamer pipeline: v4l2src name=video_source device=/dev/video0 ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1    ! appsink name=ofappsink caps="video/x-raw, format=RGB, width=640, height=480"
[ error ] ofxXmlSettings: pushTag(): tag "movie" not found
[ error ] Movie filename tag not set in settings, reverting to camera input
[ error ] ofxXmlSettings: pushTag(): tag "face" not found
 and i copy and paste the model in contain folder is bin\data\model...........pls i need u r help as soon as possible

**Comment by kylemcdonald** [comment]
it looks like you don't have `settings.xml` in the `bin/data/` folder. please make sure it's there.

**Comment by manojprabhakaran1** [comment]
thank u kylemcdonald, i got the output,and  i also  done the shapemesh of the face tarcking...
how can to get the feature points in xyz directon and xy direction  and it print the axis in text file ....i need u r help....

**Comment by manojprabhakaran1** [comment]
how to give the movie file path....i gave it in "megamind.mov" file in location of bin/data/ sir, but it showing error its not found in the current context....
