### ISSUE TITLE
setHaarMinSize not working?

### ISSUE THREAD

**Issue by antimodular** [kylemcdonald/ofxFaceTracker#88]
i have tried to feed numbers from 10 to 20000000 to tracker. setHaarMinSize(10);
but it still returns faces that are super far away; i.e. super small.

i call faceTracker.reset(); once in a while but this should not effect the setHaarMinSize, right?
thx,

**Comment by kylemcdonald** [comment]
can you paste a small example of code that has this behavior? i cannot reproduce this bug.

**Comment by antimodular** [comment]
i added this to your example-extraction

```
void testApp::mouseMoved(int x, int y){
    tracker.reset();
    tracker.setHaarMinSize(mouseX);
    cout<<"mouseX "<<mouseX<<endl;
}
```

but i have to mention that i am using #include "ofxFaceTrackerThreaded.h" which seems to creates the problem.

**Comment by kylemcdonald** [comment]
i think i just fixed this one. sorry, ofxFaceTrackerThreaded works in a way that it's easy for it to get out of sync with the ofxFaceTracker API

**Comment by antimodular** [comment]
not sure if it is really fixed.
i still get strange behaviour. it's hard to tell if it works somehow or not at all.
somewhere around 180 it allows for big faces and very small faces. and when i got bigger than 200 i have to be super close to the cam to get a face. ?thx

**Comment by kylemcdonald** [comment]
hmm, as far as i could tell it was working... if you can reproduce with a photo and post an example where the photo is not correctly tracked, i can try to fix it.
