### ISSUE TITLE
iOS realtime performance

### ISSUE THREAD

**Issue by araid** [kylemcdonald/ofxFaceTracker#93]
Not really an issue, and I know it has been commented sometimes, but I wanted to ask for specific pointers or optimizations that could help run this close to realtime on iOS, even if at the cost of lower accuracy.

I'm currently on iOS 8.3 and I can't reach 10fps on the last iPod Touch. Threaded tracking seems to run at the same speed, just out of sync with the image. I have also tried setting the input to the lowest resolution.

Thanks!

**Comment by kylemcdonald** [comment]
the only solution is to significantly resize the camera resolution, even after you have set the resolution as small as possible. sorry there are no magic tricks!

**Comment by maniyarpayal** [comment]
Is this repository available for iPhone?
