### ISSUE TITLE
  'getPixelsRef' : is not a member of 'ofBaseHasPixels_<T>'

### ISSUE THREAD

**Issue by kevincleve** [kylemcdonald/ofxFaceTracker#94]
hello! when i run the all examples on windows,there is one common error in the following code:
template <class T> inline Mat toCv(ofBaseHasPixels_<T>& img) {
	return toCv(img.getPixelsRef());
}
in  utilities.h.
how should i fix this?
can you give me some suggestions?

**Comment by erdii** [comment]
i've got the same error in fedora 21

**Comment by kylemcdonald** [comment]
it sounds like you might be using ofxFaceTracker with a newer version of OF. try using the `develop` branch of ofxFaceTracker instead.

**Comment by erdii** [comment]
I'm afraid I couldn't find the develop branch of ofxFaceTracker.

![ofxfacetracker-branches](https://cloud.githubusercontent.com/assets/5539202/8359333/e7207782-1b65-11e5-9722-949d9a8c3663.PNG)

Could you point it out to me please?
Thanks in advance!

**Comment by kylemcdonald** [comment]
of sorry, i meant the develop branch of ofxCv -- this is not an ofxFaceTracker bug, the error occurs inside the ofxCv Mat conversion function.
