### ISSUE TITLE
Using addon with KinectV2

### ISSUE THREAD

**Issue by RitterLean** [kylemcdonald/ofxFaceTracker#95]
Hey,

i want to use the IR input of the KinectV2. The Device is already set up and running but I have no Idea how to use anything from the Kinect V2 with the facetracker. I tried to hook up kinect0 instead of videograbber cam but this did not work at all. I now replaced cam with tracker.update(toCv(kinect0.getColorPixelsRef()));
![bildschirmfoto 2015-05-15 um 17 26 36](https://cloud.githubusercontent.com/assets/12255509/7656063/6834a0cc-fb28-11e4-8b68-500790a97042.png)
It compiles but then this shows up:
![bildschirmfoto 2015-05-15 um 17 25 54](https://cloud.githubusercontent.com/assets/12255509/7656077/77014e48-fb28-11e4-9b01-018888e08fa8.png)

I'm totally new to openframeworks and I am thankful for every help you guys can give me. I know this is not an issue specificly connected to this addon but maybe someone can help

Peace

**Comment by kylemcdonald** [comment]
this looks like it's specific to kinect v2 having 0 width and height for some reason. can't help with that, sorry!
