### ISSUE TITLE
face get's stuck

### ISSUE THREAD

**Issue by antimodular** [kylemcdonald/ofxFaceTracker#99]
Hi.
I have 9 webcam streams open, each doing their own face detection via ofxFaceTrackerThreaded.
At times it happens that one feed sees a face and does not let go of it.
Here are 2 screen shots showing the stuck face in the middle stream.

Is there a way to reset the tracker?
calling reset() does not help.

thanks
![screen shot 2015-09-15 at 2 37 59 pm](https://cloud.githubusercontent.com/assets/3649364/9886332/b5a2fbf2-5bb7-11e5-92ff-6887f6042682.png)
![screen shot 2015-09-15 at 2 37 39 pm](https://cloud.githubusercontent.com/assets/3649364/9886333/b5a7aff8-5bb7-11e5-8b3c-89c66c048112.png)

**Comment by kylemcdonald** [comment]
first off: omg.

second: just fixed this. it looks like it was only half-implemented it (the `needsResetting` flag was there, but there was no way to set it). i think "master" should work with 0.8.4 but i haven't checked. this fix and other recent changes are in "develop". sorry the branch structure is a bit messy.

**Comment by antimodular** [comment]
thanks so much.
